# Generated by Django 2.0.3 on 2018-11-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books_Model',
            new_name='Post',
        ),
    ]
