# Generated by Django 2.0.3 on 2018-11-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20181128_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('title',)},
        ),
    ]
