# Generated by Django 2.0.3 on 2018-11-29 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20181128_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Post owner'),
            preserve_default=False,
        ),
    ]
